### ISSUE TITLE
Implement rr:class support

### ISSUE THREAD

**Issue by w0xter** [oeg-upm/morph-csv#39]
We can add the rr:class of the subject maps  from the generated R2RML applying a regex to the ttl file searching for the names of the ObjectMaps correspondings with each subject to include the rdf:type of the subject using the rr:class predicate

**Comment by w0xter** [comment]
Instead of use regex it will be more easier load the generated r2rml mapping into a rdflib Graph and add rr:class predicate to the subject maps

**Comment by dachafra** [comment]
solved in yarrrrml parser
