### ISSUE TITLE
Review why FK are not being applied

### ISSUE THREAD

**Issue by dachafra** [oeg-upm/morph-csv#40]
For example, in Q9 of GTFS-MAdrid-Benh FK should be created (and they are declared in the CSVW) but the morph-csv output does not contain any PK
https://morph.oeg.fi.upm.es/demo/morphcsv/run/gtfs/9
```
"foreignKey": [
          {
            "columnReference": "route_id",
            "reference": {
              "resource": "/data/ROUTES.csv",
              "columnReference": "route_id"
            }
          },
          {
            "columnReference": "shape_id",
            "reference": {
              "resource": "/data/SHAPES.csv",
              "columnReference": "shape_id"
            }
          },
          {
            "columnReference": "service_id",
            "reference": {
              "resource": "/data/CALENDAR.csv",
              "columnReference": "service_id"
            }
          },
          {
            "columnReference": "service_id",
            "reference": {
              "resource": "/data/CALENDAR_DATES.csv",
              "columnReference": "service_id"
            }
          }
        ],
```

**Comment by dachafra** [comment]
Aham, I found that they are actually created (taking a look to the schemas) but they are not shown in the landing page, neither the FK number nor the correct schema  ;-)

ALTER TABLE trips ADD FOREIGN KEY (route_id) REFERENCES routes (route_id);
ALTER TABLE trips ADD FOREIGN KEY (service_id) REFERENCES calendar (service_id);
ALTER TABLE trips ADD FOREIGN KEY (service_id) REFERENCES calendar_dates (service_id);

**Comment by dachafra** [comment]
So, I would suggest moving the issue to the website of morph (don't know if it is morph-website or morph-csv-demo)

**Comment by w0xter** [comment]
I'm reviewing it. In the simplified  CSVW of the website doesn't appear any foreign key, I'll run everything again to check if in the generated CSVW appears the foreigns keys

**Comment by dachafra** [comment]
I don't know in the actual CSVW, but the annotations above are extracted from the website, from the simplified CSVW (query9)

**Comment by w0xter** [comment]
Okay I've just realized the error,[ I'm checking the the "foreignKeys" field but not the "foreignKey" field](https://github.com/oeg-upm/morph-website/blob/405358d8c63848f46089be5a080a84a7cada0e6f/morph-group/src/morphCsvComponent/components/query/QueryCharts.js#L34) :sweat_smile: :sweat_smile:

**Comment by dachafra** [comment]
found the issue, closing it, as it isn't part directly from morph-csv, thanks @w0xter
